name: Go-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        branch: [main, testify, ginkgo, testcontainers]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Git checkout
        run: git checkout ${{ matrix.branch }}

      - name: Build
        run: go build -v ./...

      - name: Test with the Go CLI
        run: go test -v timeout=300s ./... 
